### ISSUE TITLE
Command Fails to work

### ISSUE THREAD

**Issue by cmar7945** [lofi-nomi/ServerVeinMine#2]
When using Config command, serverside gives error on /config command. fresh install

**Comment by 3g3g33g** [comment]
use /cconfig

**Comment by cmar7945** [comment]
Thats the point. The /config command isn't recognized!

**Comment by cmar7945** [comment]
Thats the thing.. the /config command isnt recognized by minecraft on a private server. says theres a syntax error and all i type in is /config

**Comment by nayomaise** [comment]
What version, server version and mod version. Please provide logs after attempting /config serverveinmine veinMineableBlocks get
